backend:
  name: git-gateway
  branch: staging
  accept_roles:
    - admin
    - editor
media_folder: static/images/uploads
public_folder: /images/uploads
publish_mode: editorial_workflow
show_preview_links: true
collections:
  - name: meta_data
    label: Meta data
    folder: resources/content/meta
    create: false
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - name: head
        label: SEO <head /> data
        widget: object
        fields:
          - name: title
            label: Site title tag value
            widget: string
          - name: meta
            label: Meta tags
            label_singular: Meta tag
            widget: list
            fields:
              - name: name
                label: name attribute
                widget: string
              - name: content
                label: Content attribute, if no value is given then value will be taken from "File"
                widget: string
                required: false
                default: ""
              - name: file
                label: File
                description: Used instead of content where the meta tag is a URL to a file such as image etc.
                required: false
                default: ""
                widget: file
                allow_multiple: false
  - name: header
    label: Header
    folder: resources/content/header
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - name: navigation
        label: Navigation
        widget: object
        fields:
          - name: labels
            label: Navigation links text
            widget: object
            fields:
              - name: home
                label: Home page
                widget: string
              - name: page_2
                label: Page 2
                widget: string
  - name: footer
    label: Footer
    folder: resources/content/footer
    create: false
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: cardano_info
        name: Cardano info heading
        widget: string
      - label: Community email address
        name: community_email
        widget: string
      - name: community_info
        label: Community info heading
        widget: string
      - label: Cardano informational links
        label_singular: Cardano informational link
        name: cardano_links
        widget: list
        fields:
          - label: URL
            name: href
            widget: string
          - label: Label
            name: label
            widget: string
      - label: Cardano community links
        label_singular: Cardano community link
        name: community_links
        widget: list
        fields:
          - label: URL
            name: href
            widget: string
          - label: Label
            name: label
            widget: string
      - label: Footer text
        name: body
        description: Text blob in footer, parsed as HTML
        widget: string
  - name: home_page
    label: Home page
    folder: resources/content/pages/index
    create: false
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - name: content
        label: Home page content
        widget: object
        fields:
          - name: title
            label: Main title
            widget: string
          - name: page_2_link
            label: Page 2 link text
            widget: string
  - name: 404_page
    label: 404 page
    folder: resources/content/pages/404
    create: false
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - name: content
        label: 404 page content
        widget: object
        fields:
          - name: title
            label: Title
            widget: string
          - name: subtitle
            label: Subtitle
            widget: string
          - name: description
            label: description
            widget: string
